export default {
  // FONT
  FONT_SIZE_EXTRA_SMALL: 12,
  FONT_SIZE_SMALL: 14,
  FONT_SIZE_NORMAL: 16,
  FONT_SIZE_MEDIUM: 18,
  FONT_SIZE_LARGE: 20,
  FONT_SIZE_EXTRA_LARGE: 22,

  // FONT FAMILY
  FONG_FAMILY: 'DM Sans',

  // COLORS
  PRIMARY_COLOR: '#1B2F5D',
  LIGHT_PRIMARY_COLOR: '#2031598F',
  WHITE_COLOR: '#FFFFFF',
  SECOND_WHITE_COLOR: '#FBE9E770',
  BLACK_COLOR: '#000000',
  TEXT_COLOR: '#3E5481',
  LIGHT_TEXT_COLOR: '#1B2F5DBF',
  ICON_COLOR: '#03053D',
  GREY: '#C4C4C4',

  // WEIGHT
  FONT_WEIGHT_LIGHT: '500',
  FONT_WEIGHT_MEDIUM: '700',
  FONT_WEIGHT_HEAVY: 'bold',

  // BORDER RADIUS
  IMAGE_BORDER_RADIUS: 5,
  BUTTON_BORDER_RADIUS: 8,
  PROFILE_IMAGE_BORDER_RADIUS: 99,
};
